name: "Run go test"
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'
      - 
        name: Install dependencies
        run: go get .
      - 
        name: Build
        run: go build -v ./...
      # - 
      #   name: Run Unit Tests
      #   run: go test ./latitudesh -v -timeout 10m -run "TestProvider|TestFrameworkProvider"
  
  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - 
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.23.0'
      - 
        name: Install dependencies
        run: go get .
      - 
        name: Run E2E Tests
        run: go test ./latitudesh -v -timeout 60m -run "TestAccEnvVarAuthTokenSet|TestAccServerUserDataValidation|TestAccServer|TestAccTag|TestAccSSHKey|TestAccDataSourceSSHKey|TestAccDataSourcePlan"
        env:
          TF_ACC: '1'
          LATITUDESH_AUTH_TOKEN: ${{ secrets.LATITUDESH_AUTH_TOKEN }}
          LATITUDESH_TEST_PROJECT: ${{ secrets.LATITUDESH_TEST_PROJECT }}
